### ISSUE TITLE
Find a nice way to have "classes" in C

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Gigabyte-Giant/Glang#10]
Now, one of the first things that might come to someone's mind when they see this, would be "use C++ (or D)", but, I don't want to use either one of those (for now, at least).

I always find it fun to try and create makeshift "classes" in C, as it's not too terribly difficult if you understand the concept behind a class.

**Comment by Gigabyte-Giant** [comment]
So, the basic idea behind what I'm thinking, looks something like follows:

```c
struct someFakeClassStruct
{
    // Declare properties and/or functions
};

typedef struct someFakeClassStruct someFakeClass;
```

That's super easy, now all we'll need to do is replicate the `new` keyword...

```c
someFakeClass *createSomeFakeClass()
{
    someFakeClass tmpClass;

    // Initialize properties

    return &tmpClass;
}
```

**Comment by MikaalSky** [comment]
No no.
We just need more Teacher instances.
The problem should resolve itself.

**Comment by Gigabyte-Giant** [comment]
I think I've found a nice way to replicate basic "classes", in C, so I'll go ahead and mark this as complete.
