### ISSUE TITLE
Dynamic-ish arrays

### ISSUE THREAD

**Issue by Gigabyte-Giant** [Gigabyte-Giant/Glang#12]
When I was using C++ for Glang, I was using `std::vector`s to keep any lists that I needed.

Since we've moved over to C, I think it'll be a good idea to go ahead and create some "helper functions" that'll give us makeshift "dynamic arrays". By "dynamic", I mean, allowing us to at least push items onto them.

**Comment by Gigabyte-Giant** [comment]
I have a **super simple** dynamic array "thing" working as-per https://github.com/G-lang/Glang/commit/e3a75b3890453c6bb7f28a53e936894cd3d921ea. I'm sure I'll be adding more to it over time, but, for now, I'm going to mark this as complete.

**Comment by MikaalSky** [comment]
Ok thx

**Comment by MikaalSky** [comment]
do I get my array of strings yet or do I have to wait for that too

**Comment by Gigabyte-Giant** [comment]
Arrays of strings are supported, they're just not very easy to do, as you'll have to set a *hard limit* on how long the strings can be, and then you'll have to make sure your strings don't exceed that limit. Here's an example:

```c
int MAX_STR_LEN = 256; // The maximum length of a string

dynArray *myArrayOfStrings = createArray(sizeof(char) * (MAX_STR_LEN));

myArrayOfStrings->push(myArrayOfStrings, "some string");
myArrayOfStrings->push(myArrayOfStrings, "some other string");

for (int i = 0; i < myArrayOfStrings->length; i++)
{
    printf("String at index %d: %s\n", i, (char *) myArrayOfStrings->at(myArrayOfStrings, i));
}

destroyArray(myArrayOfStrings);
```

**Comment by MikaalSky** [comment]
Heck no, I'm having infinitely long strings. >:( you can't tell me what to do

**Comment by Gigabyte-Giant** [comment]
I don't really see where Glang would need to have support for arrays of "infinitely long strings", so I think what we have right now, will be fine.

Also, it's technically impossible to have an "infinitely long" string, as you're limited by the amount of memory that you have on your machine.

**Comment by MikaalSky** [comment]
The Cloud will save me >:(

**Comment by JavascriptFTW** [comment]
The cloud is o vacation. :)

**Comment by Gigabyte-Giant** [comment]
Even the magical cloud has limitations @MikaalSky-- something that you'll learn soon enough!
