### ISSUE TITLE
Everything should be mutable unless specifically stated.

### ISSUE THREAD

**Issue by MikaalSky** [Gigabyte-Giant/Glang#13]
Because it's annoying.

**Comment by Gigabyte-Giant** [comment]
Yeah, there'll most likely be a `const` keyword or something like that, which will be used to specify variables that should never change.

**Comment by Gigabyte-Giant** [comment]
I'm going to close this, as this has nothing to do with this repository.
In the future, if you have any questions, comments, or suggestions regarding Glang's language specification, please file them under [this repository](https://github.com/Gigabyte-Giant/Glang-Specification).
