### ISSUE TITLE
Consistent Types

### ISSUE THREAD

**Issue by MikaalSky** [Gigabyte-Giant/Glang#14]
Let's not do as Swift.
Swift likes to make you use NSNumber of NSString instead of flat out String or int. It will make everyone happier if we don't do this.

**Comment by Gigabyte-Giant** [comment]
To start, I think Glang is going to be a loosely-typed language (like Javascript, or Perl)-- however, that being said, I eventually want/need this to be a strictly-typed language.

Thanks for the input @MikaalSky!

**Comment by MikaalSky** [comment]
We could have "var" just be a "okay screw it, whatever is fine" keyword and then have type-specific keywords.

**Comment by Gigabyte-Giant** [comment]
> We could have "var" just be a "okay screw it, whatever is fine" keyword and then have type-specific keywords.

So, you're sort-of leaning towards the view(s) expressed in https://github.com/G-lang/Glang/issues/15?

**Comment by MikaalSky** [comment]
Yea but not entirely.

**Comment by Gigabyte-Giant** [comment]
...as this issue has nothing to do with this specific repository, I'm going to close this.

In the future, please place file any questions, comments, and/or suggestions you have regarding Glang's language specification, under [this repository](https://github.com/Gigabyte-Giant/Glang-Specification).

Thank you for your interest in the Glang project.
