### ISSUE TITLE
Change name from G-lang to Glang

### ISSUE THREAD

**Issue by inkblotty** [Gigabyte-Giant/Glang#19]
'Glang' should be consistent throughout the entire project.

**Comment by Cis112233** [comment]
I have gone into the code and I checked and I found no places using G-lang in any files.

**Comment by inkblotty** [comment]
The entire organization is still called G-lang.

**Comment by Gigabyte-Giant** [comment]
The code itself most likely doesn’t have any instances of “G-Lang”, however, as Katie pointed out, the entire organization is called “G-Lang”.

Apart from changing that, I’m also considering changing the name of the language all-together…

**Comment by Cis112233** [comment]
Glang is the best tho

**Comment by Gigabyte-Giant** [comment]
...I'm going to close this, as the organization in question, doesn't exist anymore.
